ascend:
- diopiAbs
- diopiAbsInp
- diopiAdaptiveAvgPool2d
- diopiAdaptiveAvgPool2dBackward
- diopiAddcdiv
- diopiAddcdivInp
- diopiAddcmul
- diopiAddcmulInp
- diopiAddmm
- diopiAll
- diopiAny
- diopiArange
- diopiArgmax
- diopiBaddbmm
- diopiBaddbmmInp
- diopiBitwiseAnd
- diopiBitwiseNot
- diopiBmm
- diopiCastDtype
- diopiCat
- diopiClamp
- diopiClampInp
- diopiClampInpScalar
- diopiClampMax
- diopiClampMaxInp
- diopiClampMaxInpScalar
- diopiClampMaxScalar
- diopiClampMin
- diopiClampMinInp
- diopiClampMinInpScalar
- diopiClampMinScalar
- diopiClampScalar
- diopiContiguous
- diopiCopyInp
- diopiCos
- diopiCosInp
- diopiCrossEntropyLoss
- diopiCrossEntropyLossBackward
- diopiDiv
- diopiDivInp
- diopiDivInpScalar
- diopiDivScalar
- diopiDropout
- diopiEmbedding
- diopiEmbeddingBackward
- diopiEq
- diopiEqInp
- diopiEqInpScalar
- diopiEqScalar
- diopiErf
- diopiErfInp
- diopiExp
- diopiExpInp
- diopiFill
- diopiFlip
- diopiFloor
- diopiFloorInp
- diopiGather
- diopiGe
- diopiGeInp
- diopiGeInpScalar
- diopiGeScalar
- diopiGelu
- diopiGeluBackward
- diopiGroupNorm
- diopiGt
- diopiGtInp
- diopiGtInpScalar
- diopiGtScalar
- diopiHardtanh
- diopiHardtanhBackward
- diopiHardtanhInp
- diopiIndexSelect
- diopiIsNan
- diopiLayerNorm
- diopiLayerNormBackward
- diopiLe
- diopiLeInp
- diopiLeInpScalar
- diopiLeScalar
- diopiLeakyRelu
- diopiLeakyReluBackward
- diopiLeakyReluInp
- diopiLinear
- diopiLinearBackward
- diopiLog
- diopiLog10
- diopiLog10Inp
- diopiLog2
- diopiLog2Inp
- diopiLogInp
- diopiLogSoftmax
- diopiLogSoftmaxBackward
- diopiLogicalAndInp
- diopiLogicalNot
- diopiLogicalNotInp
- diopiLogicalOrInp
- diopiLt
- diopiLtInp
- diopiLtInpScalar
- diopiLtScalar
- diopiMSELoss
- diopiMSELossBackward
- diopiMaskedFill
- diopiMaskedFillInp
- diopiMaskedFillInpScalar
- diopiMaskedFillScalar
- diopiMax
- diopiMaxAll
- diopiMaximum
- diopiMean
- diopiMin
- diopiMinAll
- diopiMinimum
- diopiMm
- diopiMul
- diopiMulInp
- diopiMulInpScalar
- diopiMulScalar
- diopiMultinomial
- diopiNLLLoss
- diopiNLLLossBackward
- diopiNe
- diopiNeInp
- diopiNeInpScalar
- diopiNeScalar
- diopiNeg
- diopiNegInp
- diopiNonzero
- diopiNormalScalarTensor
- diopiNormalTensor
- diopiNormalTensorScalar
- diopiOneHot
- diopiPermute
- diopiPow
- diopiPowInp
- diopiPowInpTensor
- diopiPowScalar
- diopiPowTensor
- diopiReciprocal
- diopiReciprocalInp
- diopiRelu
- diopiReluInp
- diopiRsqrt
- diopiRsqrtInp
- diopiSgn
- diopiSgnInp
- diopiSigmoid
- diopiSigmoidBackward
- diopiSigmoidInp
- diopiSilu
- diopiSiluBackward
- diopiSiluInp
- diopiSin
- diopiSinInp
- diopiSlice
- diopiSliceBackward
- diopiSoftmax
- diopiSoftmaxBackward
- diopiSort
- diopiSqrt
- diopiSqrtInp
- diopiSub
- diopiSubInp
- diopiSubInpScalar
- diopiSubScalar
- diopiSum
- diopiTanh
- diopiTanhBackward
- diopiThreshold
- diopiThresholdBackward
- diopiThresholdInp
- diopiTopk
- diopiTranspose
- diopiTril
- diopiTriu
- diopiTriuInp
- diopiUniformInp
- diopiUpsampleLinear
- diopiUpsampleLinearBackward
- diopiUpsampleNearest
- diopiUpsampleNearestBackward
- diopiWhere
- diopiBatchNorm
- diopiBatchNormBackward
- diopiAdd
- diopiAddInp
- diopiAddScalar
- diopiAddInpScalar
- diopiConvolution2d
- diopiConvolution2dBackward
- diopiLogicalAnd
- diopiLogicalOr
- diopiExpand
- diopiLinspace
- diopiProd
- diopiSplitWithSizes
- diopiScatter
- diopiScatterInp
- diopiScatterScalar
- diopiScatterInpScalar
- diopiApplyPenalty
ascend_npu:
- diopiRemainderTensor
- diopiRemainderScalar
- diopiRemainder
- diopiRepeat
- diopiStack
- diopiNormal
- diopiNormalInp
- diopiNorm
- diopiMaxPool2dWithIndices
- diopiRotaryEmbedding
