ascend:
- diopiAbs
- diopiAbsInp
- diopiAdd
- diopiAddInp
- diopiAddScalar
- diopiAddInpScalar
- diopiAddcdiv
- diopiAddcdivInp
- diopiAll
- diopiAny
- diopiArange
- diopiArgmax
- diopiAtan
- diopiAtanInp
- diopiBitwiseNot
- diopiBitwiseNotInp
- diopiBitwiseAnd
- diopiBitwiseAndInp
- diopiBitwiseAndScalar
- diopiBitwiseAndInpScalar
- diopiBitwiseOr
- diopiBitwiseOrInp
- diopiBitwiseOrScalar
- diopiBitwiseOrInpScalar
- diopiCastDtype
- diopiCeil
- diopiCeilInp
- diopiCol2Im
- diopiContiguous
- diopiConvolution2d
- diopiConvolution2dBackward
- diopiCos
- diopiCosInp
- diopiCrossEntropyLoss
- diopiCrossEntropyLossBackward
- diopiCumsum
- diopiDiv
- diopiDivInp
- diopiDivInpScalar
- diopiDivScalar
- diopiEmbedding
- diopiEmbeddingBackward
- diopiFlip
- diopiEq
- diopiEqInp
- diopiEqInpScalar
- diopiEqScalar
- diopiEqual
- diopiErf
- diopiErfInp
- diopiExp
- diopiExpInp
- diopiFill
- diopiFloor
- diopiFloorInp
- diopiGather
- diopiGe
- diopiGeInp
- diopiGeInpScalar
- diopiGelu
- diopiGeluBackward
- diopiGeScalar
- diopiGt
- diopiGtInp
- diopiGtInpScalar
- diopiGtScalar
- diopiHardswish
- diopiHardswishInp
- diopiHardswishBackward
- diopiHardtanh
- diopiHardtanhBackward
- diopiHardtanhInp
- diopiIsNan
- diopiLayerNorm
- diopiLayerNormBackward
- diopiLeakyRelu
- diopiLeakyReluBackward
- diopiLeakyReluInp
- diopiLerpTensor
- diopiLerpScalar
- diopiLinalgVecNorm
- diopiLinear
- diopiLinearBackward
- diopiLe
- diopiLeInp
- diopiLeInpScalar
- diopiLeScalar
- diopiLogSoftmax
- diopiLogSoftmaxBackward
- diopiLogicalAnd
- diopiLogicalOr
- diopiLogicalAndInp
- diopiLogicalOrInp
- diopiLogicalNot
- diopiLogicalNotInp
- diopiLt
- diopiLtInp
- diopiLtInpScalar
- diopiLtScalar
- diopiMean
- diopiMSELoss
- diopiMSELossBackward
- diopiMul
- diopiMulInp
- diopiMulInpScalar
- diopiMulScalar
- diopiNe
- diopiNeInp
- diopiNeInpScalar
- diopiNeScalar
- diopiNormal
- diopiNormalInp
- diopiLinspace
- diopiLog
- diopiLog10
- diopiLog10Inp
- diopiLog2
- diopiLog2Inp
- diopiLogInp
- diopiNeg
- diopiNegInp
- diopiNormalScalarTensor
- diopiNormalTensor
- diopiNormalTensorScalar
- diopiReciprocal
- diopiReciprocalInp
- diopiRelu
- diopiReluInp
- diopiRMSNorm
- diopiRMSNormBackward
- diopiRsqrt
- diopiRsqrtInp
- diopiSgn
- diopiSgnInp
- diopiSigmoid
- diopiSigmoidBackward
- diopiSigmoidInp
- diopiOnes
- diopiPermute
- diopiProd
- diopiRemainder
- diopiRemainderScalar
- diopiRemainderTensor
- diopiRepeat
- diopiSlice
- diopiSliceBackward
- diopiSplitWithSizes
- diopiSub
- diopiSubInp
- diopiSubInpScalar
- diopiSubScalar
- diopiSum
- diopiSort
- diopiSqrt
- diopiSqrtInp
- diopiTanh
- diopiTanhBackward
- diopiTanhInp
- diopiSilu
- diopiSiluInp
- diopiSiluBackward
- diopiSin
- diopiSinInp
- diopiSoftmax
- diopiSoftmaxBackward
- diopiThreshold
- diopiThresholdBackward
- diopiThresholdInp
- diopiTranspose
- diopiTril
- diopiTriu
- diopiTriuInp
- diopiTopk
- diopiUniformInp
- diopiWhere
- diopiZeroInp
- diopiZeros
ascend_npu:
- diopiAdamW
- diopiAdaptiveAvgPool2d
- diopiAdaptiveAvgPool2dBackward
- diopiAddcmul
- diopiAddcmulInp
- diopiAddmm
- diopiBaddbmm
- diopiBaddbmmInp
- diopiBatchNorm
- diopiBatchNormBackward
- diopiNonzero
- diopiBmm
- diopiMatmul
- diopiMaxAll
- diopiMin
- diopiMinAll
- diopiMinimum
- diopiCat
- diopiDropout
- diopiDropoutInp
- diopiCopyInp
- diopiExpand
- diopiGroupNorm
- diopiGroupNormBackward
- diopiMax
- diopiMaximum
- diopiMaskedFill
- diopiMaskedFillInp
- diopiMaskedFillInpScalar
- diopiMaskedFillScalar
- diopiStack
- diopiMultinomial
- diopiNorm
- diopiMaxPool2dWithIndices
- diopiRotaryEmbedding
- diopiIndexPut
- diopiIndexPutInp
- diopiIndexSelect
- diopiIndexSelectBackward
- diopiIndex
- diopiIndexBackward
- diopiDestIndexCopyKV
- diopiTokenAttentionInference
- diopiTokenSoftmaxReduceVInference
- diopiApplyPenalty
- diopiContextAttentionInference
- diopiNativeMemoryFormatCast
- diopiGetNativeMemoryFormat
- diopiTensorDestructionHook
- diopiMaskedSelect
- diopiMaskedSelectBackward
- diopiMm
- diopiNLLLoss
- diopiNLLLossBackward
- diopiNLLLossV2
- diopiNLLLossV2Backward
- diopiOneHot
- diopiScatter
- diopiScatterInp
- diopiScatterScalar
- diopiScatterInpScalar
- diopiClamp
- diopiClampInp
- diopiClampInpScalar
- diopiClampMax
- diopiClampMaxInp
- diopiClampMaxInpScalar
- diopiClampMaxScalar
- diopiClampMin
- diopiClampMinInp
- diopiClampMinInpScalar
- diopiClampMinScalar
- diopiClampScalar
- diopiUpsampleLinear
- diopiUpsampleLinearBackward
- diopiUpsampleNearest
- diopiUpsampleNearestBackward
- diopiPow
- diopiPowInp
- diopiPowInpTensor
- diopiPowScalar
- diopiPowTensor
- diopiFlashAttention
- diopiFlashAttentionBackward
- diopiFlashAttentionV2
- diopiFlashAttentionVarLen
- diopiFlashAttentionVarLenBackward
- diopiScaledMaskedSoftmax
- diopiScaledMaskedSoftmaxBackward
